### ISSUE TITLE
Ampersand is not escaped in xml

### ISSUE THREAD

**Issue by okater** [acibilous/sfcc-catalog-reducer#4]
Ampersand is not escaped in xml
Should be escaped as `$amp;`
![image](https://user-images.githubusercontent.com/49038464/191089129-b50f77e0-4838-4c28-affc-941a0cbd630d.png)

Results in error during import

**Comment by hryhola** [comment]
Did you mean that _\&amp;_ string should be replaced with _$amp;_?
It's impossible to run the script if some attribute value contains exact _&_ symbol - sax parser will receive an error.
<img width="731" alt="Untitled" src="https://user-images.githubusercontent.com/44097600/191255423-48abc5be-3fb3-4327-b91d-d37b353ff4ee.png">

**Comment by maxjf1** [comment]
The problem happens with me too. 

navigation xml before reducing:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/6114888/202750733-bfe95086-5a1d-4120-b083-bb24bd889913.png">

After reducing:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/6114888/202750831-9088eb45-5f48-4fa7-b104-d1fe76c85d78.png">

When uploading to SFCC it gives an XML error. Manually replacing the `& ` to `&amp;` fixes it

**Comment by zhornyk** [comment]
Issue was fixed. NPM package was updated to v2.1.0
